# Generated by Django 4.1.7 on 2023-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approval_from_RMD',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_doses',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_doses_administered',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='patient_edu_res_brought',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='patient_edu_res_distributed',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('working', 'Working'), ('cancelled', 'Cancelled')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vaccines_offered',
            field=models.CharField(choices=[('COVID', 'COVID'), ('FLU', 'FLU'), ('M POX', 'M POX')], max_length=5, null=True),
        ),
    ]
